name: yaanam
description: "Trip Management Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  google_fonts: ^6.2.0
  flutter_svg: ^2.2.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  equatable: ^2.0.7
  favicon: ^1.1.2
#  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  awesome_dialog: ^3.2.1
  google_maps_flutter: ^2.16.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/yaanam/png/
    - assets/images/yaanam/svg/
